# Generated by Django 3.2.18 on 2023-04-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='write',
            name='blog_img',
        ),
        migrations.RemoveField(
            model_name='write',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='write',
            name='description',
        ),
        migrations.RemoveField(
            model_name='write',
            name='title',
        ),
        migrations.RemoveField(
            model_name='write',
            name='update_at',
        ),
        migrations.AddField(
            model_name='write',
            name='myWrite',
            field=models.ManyToManyField(to='writeblog.Blog'),
        ),
    ]
