# Generated by Django 3.2.18 on 2023-04-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blogger'),
        ('writeblog', '0002_auto_20230407_0934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogWrite',
        ),
        migrations.RenameModel(
            old_name='Write',
            new_name='Writer',
        ),
    ]
