# Generated by Django 3.2.18 on 2023-04-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeblog', '0002_auto_20230410_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogwrite',
            name='like',
        ),
    ]
