# Generated by Django 3.2.18 on 2023-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeblog', '0003_auto_20230407_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogwrite',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
