# Generated by Django 3.2.18 on 2023-04-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeblog', '0004_blogwrite_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogwrite',
            name='like',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
