# Generated by Django 3.2.18 on 2023-04-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeblog', '0006_bloglike_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liker',
        ),
        migrations.DeleteModel(
            name='BlogLike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
