# Generated by Django 3.2.18 on 2023-04-10 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writeblog', '0007_auto_20230410_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogwrite',
            name='like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
