# Generated by Django 3.2.18 on 2023-04-07 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_writeblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeblog',
            name='blogger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
