# Generated by Django 3.2.18 on 2023-04-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_writeblog_blogger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Writeblog',
            new_name='Blogger',
        ),
    ]
