# Generated by Django 3.2.18 on 2023-04-07 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_writeblog_blogger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
