# Generated by Django 3.2.18 on 2023-04-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_blogger_blogger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogger',
        ),
    ]
